name: Parallel Job
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 10 && echo "First job done"
    second:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 5 && echo "Second job done"
    third:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 3 && echo "Third job done"